In [ ]:
#importamos numpy
import numpy as np

In [2]:
#Crea un arreglo de NumPy con 10 ceros.

array = np.zeros(10)

array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#Crea un arreglo de NumPy con los números del 1 al 50 y reshape en una matriz 5X10.

matrix_a = np.arange(1,51).reshape(5,10)
matrix_a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [8]:
#Dado un arreglo de NumPy, encuentra la mediana de sus elementos.
elementos = np.arange(1,26)
elementos.mean()

13.0

In [11]:
#Dado un arreglo de NumPy, multiplica todos sus elementos por 2.
matrix_elementos = np.arange(1,19).reshape(3,6)
matrix_elementos * 2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36]])

In [14]:
#Crea un arreglo de NumPy con los números del 10 al 1 en orden descendente y reshape en una matriz 5x2.
matrix_b = np.arange(1,11).reshape(5,2)
matrix_b[::-1]

array([[ 9, 10],
       [ 7,  8],
       [ 5,  6],
       [ 3,  4],
       [ 1,  2]])